---
- name: Adding /etc/hosts file entries on all the hosts
  hosts: allRockyLinux
  tasks:
  - name: generate file
    blockinfile:
      backup: yes
      path: /etc/hosts
      block: |
        {% for host in groups['allRockyLinux'] %} 
        {{ hostvars[host]['ansible_facts']['ens192']['ipv4']['address'] }} {{ hostvars[host]['ansible_facts']['hostname' + '.ros.swinfra.net'] }} {{ hostvars[host]['ansible_facts']['hostname'] }} 
        {% endfor %}