---
- hosts: localhost
  become: true
  gather_facts: true

  tasks:
  - lineinfile:
      state: present
      dest: /etc/hosts
      content: |
        {% for host in groups.allRockyLinux}
        {{ host }}
        {% endfor %}