---
- name: Adding /etc/hosts file entries on all the hosts
  hosts: allRockyLinux
  tasks:
  - name: Updating the /etc/hosts file
    blockinfile:
      backup: yes
      path: /etc/hosts
      vars: 
        fqdn: '.ros.swinfra.net'
      block: |
        {% for host in groups['allRockyLinux'] %} 
        {{ hostvars[host]['ansible_facts']['ens192']['ipv4']['address'] }} {{ hostvars[host]['ansible_facts']['hostname'] + 'fqdn' }} {{ hostvars[host]['ansible_facts']['hostname'] }} 
        {% endfor %}