---
- name: Add user across specified host group
  hosts: allRockyLinux
  gather_facts: true
  vars_files:
    - /etc/ansible/playbooks/Linux_Generic/vars_usersAndGroups.yml
    
  tasks:
  - name: Task-1 - Create a group
    group:
      name: "{{ user_group }}"
      state: present
      gid: "{{ group_guid }}"
      system: false

  - name: Task-2 - Create users
    user:
      name: "{{ item }}"
      group: "{{ user_group }}"
      state: present
      create_home: true
      generate_ssh_key: true
      ssh_key_bits: 2048
      ssh_key_type: rsa
      shell: /bin/bash
      password: "{{ default_user_password | password_hash('sha512') }}" # Note that you need to complete running rpm_baremetal_provisioning.yaml
      system: false
    loop: "{{ new_users }}"
