---
- hosts: localhost
  become: true
  gather_facts: true

  tasks:
  - blockinfile:
      state: presetn
      dest: /etc/hosts
      content: |
        {% for host in groups.allRockyLinux}
        {{ host }}
        {% endfor %}