---
- name: Delete user across specified host group
  hosts: allRockyLinux
  gather_facts: true
  vars_files:
    - /etc/ansible/playbooks/Linux_Generic/vars_delete_user_groups.yml
    
  tasks:
  - name: Task-1 - Delete users
    user:
      name: "{{ item }}"
      state: absent
      remove: yes
      force: true
    loop: "{{ delete_users }}"

  - name: Task-2 - Delete a group
    group:
      name: "{{ delete_group }}"
      state: absent
